# Generated by Django 5.0.6 on 2024-06-28 20:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="content_en",
            field=models.TextField(blank=True, verbose_name="Текст статьи английский"),
        ),
        migrations.AddField(
            model_name="news",
            name="title_en",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Заголовок английский"
            ),
        ),
    ]
