# Generated by Django 5.0.6 on 2024-06-29 16:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0002_news_content_en_news_title_en"),
    ]

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Заголовок")),
                (
                    "title_en",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Заголовок английский"
                    ),
                ),
                ("content", models.TextField(verbose_name="Текст услуги")),
                (
                    "content_en",
                    models.TextField(
                        blank=True, verbose_name="Текст услуги английский"
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        upload_to="photos/%Y/%m/%d/", verbose_name="Фото"
                    ),
                ),
                (
                    "time_create",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время создания"
                    ),
                ),
                (
                    "time_update",
                    models.DateTimeField(auto_now=True, verbose_name="Время изменения"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Публикация"),
                ),
            ],
            options={
                "verbose_name": "Услуги",
                "ordering": ["-time_create", "title"],
            },
        ),
    ]
