# Generated by Django 5.0.6 on 2024-07-07 12:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0004_reviews_alter_news_options_alter_service_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="reviews",
            name="video",
            field=models.FileField(
                default=False, upload_to="video/%Y/%m/%d/", verbose_name="Видео"
            ),
            preserve_default=False,
        ),
    ]
