# Generated by Django 5.0.6 on 2024-09-15 09:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0006_service_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="slug",
            field=models.SlugField(max_length=255, verbose_name="URL"),
        ),
    ]
