# Generated by Django 5.0.6 on 2024-09-20 19:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0007_alter_service_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="price",
            field=models.IntegerField(default=10, verbose_name="Цена"),
            preserve_default=False,
        ),
    ]
