# Generated by Django 5.0.6 on 2024-09-20 20:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0008_service_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="price",
            field=models.CharField(max_length=50, verbose_name="Цена"),
        ),
    ]
