# Generated by Django 5.0.6 on 2024-09-20 22:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0009_alter_service_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="slug",
            field=models.SlugField(max_length=255, unique=True, verbose_name="URL"),
        ),
    ]
