# Generated by Django 5.0.6 on 2024-08-31 20:56

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True, max_length=250, null=True, verbose_name="Логин"
                    ),
                ),
                (
                    "telegram_phone_number",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        verbose_name="Номер телефона телеграм",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=150, null=True, verbose_name="Имя"
                    ),
                ),
                (
                    "surname",
                    models.CharField(
                        blank=True, max_length=150, null=True, verbose_name="Фамилия"
                    ),
                ),
                (
                    "patronymic",
                    models.CharField(
                        blank=True, max_length=150, null=True, verbose_name="Отчество"
                    ),
                ),
                (
                    "citizenship",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="Гражданство",
                    ),
                ),
                (
                    "appeal",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="Тип обращения",
                    ),
                ),
                (
                    "contact_phone_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Контактный номер телефона",
                    ),
                ),
                (
                    "chat_id",
                    models.BigIntegerField(unique=True, verbose_name="ID чата"),
                ),
            ],
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
    ]
