# Generated by Django 5.0.6 on 2024-08-31 21:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="telegram_phone_number",
            field=models.URLField(
                max_length=100, unique=True, verbose_name="Ссылка на телеграм"
            ),
        ),
    ]
